#pragma once

#undef NO_DEBUG
#define NO_DEBUG
#undef NO_PRINT
#define NO_PRINT
#undef NO_ACTION_MACRO
#define NO_ACTION_MACRO
#undef NO_ACTION_FUNCTION
#define NO_ACTION_FUNCTION

#undef COMBO_COUNT
#define COMBO_COUNT 1
#undef COMBO_TERM
#define COMBO_TERM 125
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 150
#undef TAPPING_TERM
#define TAPPING_TERM 150
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
